# -*- coding: utf-8 -*-
"""alura-imersao-ia2-aula3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KrZVRVK2ykRe6vfESfRRYWSL4AoYobY5

# Aula 03: Explorando os parâmetros do Google AI Studio
"""

"""
At the command line, only need to run once to install the package via pip:

$ pip install google-generativeai
"""

from pathlib import Path
import hashlib
import google.generativeai as genai

genai.configure(api_key="?????")

# Set up the model
generation_config = {
  "temperature": 0.9,
  "top_p": 0.95,
  "top_k": 32,
  "max_output_tokens": 1024,
}

safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
]

model = genai.GenerativeModel(model_name="gemini-1.0-pro-vision-latest",
                              generation_config=generation_config,
                              safety_settings=safety_settings)

prompt_parts = [
  "Given an image of a product and its target audience, write an engaging marketing description",
  "Product Image: ",
  genai.upload_file("image01.jpeg"),
  "Target Audience: Mid-aged men",
  "Marketing Description: Introducing the epitome of power and sophistication - the sleek and captivating sports car. It's more than just a car; it's a symbol of your passion for life and your unwavering commitment to excellence. Embrace the thrill and indulge in the ultimate driving pleasure.",
  "Product Image: ",
  genai.upload_file("image02.jpeg"),
  "Target Audience: Environmentalists",
  "Marketing Description: Looking for a sustainable and eco-friendly way to get around? Look no further than this black bicycle. Biking is a great way to reduce your carbon footprint and improve your health at the same time. If you're an environmentalist, there's no better way to get around than by bike!",
  "Product Image: ",
  genai.upload_file("image03.jpeg"),
  "Target Audience: Athletes",
  "Marketing Description: ",
]

response = model.generate_content(prompt_parts)
print(response.text)