# -*- coding: utf-8 -*-
"""alura_imersao_ia2_quickstart_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZuUY5FCivZZFboaw6CurVcQ5_DH091x

##### Copyright 2024 Google LLC.
"""

#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""# Gemini API Python quickstart

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://ai.google.dev/tutorials/quickstart_colab"><img src="https://ai.google.dev/static/site-assets/images/docs/notebook-site-button.png" height="32" width="32" />View on Google AI</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/google/generative-ai-docs/blob/main/site/en/tutorials/quickstart_colab.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/google/generative-ai-docs/blob/main/site/en/tutorials/quickstart_colab.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>

This tutorial shows you how to get started with the Gemini API using the Python SDK.

## Prerequisites

You can run this tutorial in Google Colab, which doesn't require additional environment configuration.

Alternatively, to complete this quickstart locally, see the Python guidance in [Get started with the Gemini API](https://ai.google.dev/tutorials/quickstart).

## Install the SDK

The Python SDK for the Gemini API is contained in the [`google-generativeai`](https://pypi.org/project/google-generativeai/) package. Install the dependency using pip:
"""

!pip install -q -U google-generativeai

"""## Set up your API key

To use the Gemini API, you'll need an API key. If you don't already have one, create a key in Google AI Studio.

<a class="button" href="https://aistudio.google.com/app/apikey" target="_blank" rel="noopener noreferrer">Get an API key</a>

In Colab, add the key to the secrets manager under the "🔑" in the left panel. Give it the name `GOOGLE_API_KEY`. Then pass the key to the SDK:
"""

# Import the Python SDK
import google.generativeai as genai
# Used to securely store your API key
from google.colab import userdata

GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)

"""## Initialize the Generative Model

Before you can make any API calls, you need to initialize the Generative Model.
"""

model = genai.GenerativeModel('gemini-pro')

"""## Generate text"""

response = model.generate_content("Vamos aprender conteúdo sobre IA. Me dê sugestões.")
print(response.text)

"""###Result print

**Recursos Online:**

* **Coursera:** Cursos de Universidades renomadas como Stanford, Caltech e Johns Hopkins.
* **edX:** Cursos de Universidades como MIT, Harvard e Berkeley.
* **Udemy:** Cursos online com opções pagas e gratuitas.
* **Udacity:** Programas de nanodegrau e cursos sobre IA e aprendizado de máquina.
* **Google AI:** Recursos de aprendizado, workshops e ferramentas de IA.

**Livros:**

* "Inteligência Artificial: Uma Abordagem Moderna" por Stuart Russell e Peter Norvig
* "Aprendizado de Máquina" por Tom Mitchell
* "Aprendizado Profundo" por Ian Goodfellow, Yoshua Bengio e Aaron Courville
* "Aprendizado de Reforço: Uma Introdução" por Richard Sutton e Andrew Barto
* "IA para Todos" por Mark St.Amant e Matt Webb

**Tutoriais e Documentação:**

* **TensorFlow:** Tutorial oficial para a popular biblioteca de aprendizado de máquina.
* **PyTorch:** Tutorial oficial para a biblioteca de aprendizado de máquina de código aberto.
* **Keras:** Documentação e tutoriais para a API de aprendizado profundo de alto nível.
* **Scikit-Learn:** Documentação e tutoriais para a biblioteca de aprendizado de máquina em Python.
* **OpenAI Gym:** Documentação e tutoriais para a plataforma de ambiente de aprendizado de reforço.

**Comunidades e Fóruns:**

* **Reddit (r/MachineLearning, r/ArtificialIntelligence):** Comunidades ativas com discussões, atualizações e suporte.
* **Stack Overflow:** Fórum para fazer e responder perguntas de programação relacionadas a IA.
* **Kaggle:** Comunidade para profissionais e entusiastas de IA, com desafios e fóruns de discussão.
* **GitHub:** Plataforma para explorar e contribuir com projetos de código aberto relacionados a IA.

"""

"""## What's next

To learn more about working with the Gemini API, see the [Python tutorial](https://ai.google.dev/tutorials/python_quickstart).

If you're new to generative AI models, you might want to look at the
[concepts guide](https://ai.google.dev/docs/concepts) and the
[Gemini API overview](https://ai.google.dev/docs/gemini_api_overview).
"""